package com.example.wazitoecommerce.navigation

const val SPLASH_URL = "splash_screen"
const val DASH_URL = "dashboard_screen"
const val AUTOREPAIR_URL = "autorepairshop_screen"
const val ADD_AUTOREPAIRSHOP_URL = "add_autorepairshop_screen"
const val VIEWAUTOSHOP_URL = "viewautoshop_screen"
const val MECHANICS_URL = "mechanics_screen"
const val ADD_MECHANIC_URL = "addmechanics_screen"
const val VIEW_MECHANIC_URL = "viewmechanics_screen"
const val ADMINLOGIN_URL = "adminlogin_screen"
const val ADMINSIGNUP_URL = "adminsignup_screen"
const val ADMINCARWSH_URL = "carwash_screen"
const val ADMINADDCARWSH_URL = "addcarwash_screen"
const val ADMINVIEWCARWSH_URL = "viewcarwash_screen"
const val ADMINGAS_URL = "gas_screen"
const val ADMINADDGAS_URL = "addgas_screen"
const val ADMINVIEWGAS_URL = "viewgas_screen"
const val ADMINTOW_URL = "tow_screen"
const val ADMINADDTOW_URL = "addtow_screen"
const val ADMINVIEWTOW_URL = "viewtow_screen"
const val ADMINROOM_URL = "showroom_screen"
const val ADMINADDROOM_URL = "addshowroom_screen"
const val ADMINVIEWROOM_URL = "viewshowroom_screen"
const val ADMINTYRE_URL = "tyre_screen"
const val ADMINADDTYRE_URL = "addtyre_screen"
const val ADMINVIEWTYRE_URL = "viewtyre_screen"
const val ADMINAUTOPART_URL = "autopart_screen"
const val ADMIN_ADDAUTOPART_URL = "add_autopart_screen"
const val ADMIN_VIEWAUTOPART_URL = "view_autopart_screen"

//user
const val USER_DASH_URL = "userdash_screen"
const val SIGNUP_URL = "signup"
const val LOGIN_URL = "login"
const val USERAUTOSHOP_URL = "userautoshop"
const val USERMECHANIC_URL = "usermechanic"
const val USERCARWSH_URL = "usercarwash"
const val USERGAS_URL = "usergas_screen"
const val USERTOW_URL = "usertow_screen"
const val USERSHOW_URL = "usershow_screen"
const val USERTYRE_URL = "usertyre_screen"
const val USERAUTOPART_URL = "userautopart_screen"

//Google

const val WEBVIEW_URL = "web view"
